(in-package :filemaid.tests)

(defun test-cli-parsing-helpers ()
  "Test CLI parsing helpers for backend and policy flags."
  (assert-true (eql :auto (filemaid::normalize-watch-backend nil))
               "default backend should be :auto")
  (assert-true (eql :poll (filemaid::normalize-watch-backend "poll"))
               "poll backend should parse")
  (assert-true (eql :inotify (filemaid::normalize-watch-backend "inotify"))
               "inotify backend should parse")
  (assert-true (eql :auto (filemaid::normalize-watch-backend "invalid"))
               "invalid backend should fallback to :auto")
  (assert-true (= 3 (filemaid::parse-positive-integer "3" 1))
               "positive integer parse should succeed")
  (assert-true (= 1 (filemaid::parse-positive-integer "0" 1))
               "zero should fallback to default")
  (assert-true (= 2 (filemaid::parse-positive-integer "abc" 2))
               "invalid integer should fallback to default")
  (assert-true (eql :error-on-conflict (filemaid::normalize-conflict-policy nil))
               "default conflict policy should be :error-on-conflict")
  (assert-true (eql :skip-on-conflict (filemaid::normalize-conflict-policy "skip-on-conflict"))
               "skip-on-conflict should parse")
  (assert-true (eql :priority (filemaid::normalize-conflict-policy "priority"))
               "priority conflict policy should parse")
  (assert-true (eql :rename (filemaid::normalize-file-conflict-policy "rename"))
               "file conflict policy rename should parse")
  (assert-true (eql :text (filemaid::normalize-diagnostics-format nil))
               "default diagnostics format should be :text")
  (assert-true (eql :json (filemaid::normalize-diagnostics-format "json"))
               "json diagnostics format should parse")
  (assert-true (filemaid::automated-mode-p (list "--yes"))
               "--yes should enable automated mode")
  (assert-true (eql (filemaid:conflict-policy)
                    (filemaid::resolve-interactive-policy nil nil))
                "no conflicts should keep configured policy"))

(defun test-conflict-profile-persistence ()
  "Test persisted profile load/save round-trip."
  (let* ((suffix (write-to-string (get-universal-time)))
         (profile-path (format nil "/tmp/filemaid-conflict-profile-~A.sexp" suffix))
         (old-path filemaid::*conflict-resolution-profile-path*)
         (old-profile filemaid::*conflict-resolution-profile*))
    (setf filemaid::*conflict-resolution-profile-path* profile-path)
    (setf filemaid::*conflict-resolution-profile* nil)
    (filemaid:conflict-profile-set "k" :left)
    (filemaid:save-conflict-resolution-profile)
    (setf filemaid::*conflict-resolution-profile* nil)
    (filemaid:load-conflict-resolution-profile :force t)
    (assert-true (eql :left (filemaid:conflict-profile-get "k"))
                 "saved conflict profile decision should reload")
    (delete-file profile-path)
    (setf filemaid::*conflict-resolution-profile-path* old-path)
    (setf filemaid::*conflict-resolution-profile* old-profile)))

(defun test-default-rules-resolution ()
  "Test fallback resolution from ~/.config/filemaid/rules equivalent path."
  (let* ((suffix (write-to-string (get-universal-time)))
         (tmp-root (format nil "/tmp/filemaid-default-rules-~A/" suffix))
         (tmp-cwd (format nil "/tmp/filemaid-empty-cwd-~A/" suffix))
         (rules-file (format nil "~Aorganization-rules.lisp" tmp-root))
         (old-global-root filemaid::*global-rules-root*)
         (old-default-rules filemaid::*default-rules-files*)
         (old-default-project filemaid::*default-project-name*))
    (ensure-directories-exist tmp-root)
    (ensure-directories-exist tmp-cwd)
    (with-open-file (stream rules-file :direction :output :if-exists :supersede :if-does-not-exist :create)
      (format stream "(in-package :filemaid)~%"))
    (setf filemaid::*global-rules-root* tmp-root)
    (setf filemaid::*default-rules-files* nil)
    (setf filemaid::*default-project-name* nil)
    (uiop:with-current-directory (tmp-cwd)
      (assert-true (probe-file (filemaid:resolve-default-rules-file))
                   "resolve-default-rules-file should detect global rules root"))
    (setf filemaid::*global-rules-root* old-global-root)
    (setf filemaid::*default-rules-files* old-default-rules)
    (setf filemaid::*default-project-name* old-default-project)
    (delete-file rules-file)
    (uiop:delete-directory-tree (uiop:ensure-directory-pathname tmp-root)
                                :validate t
                                :if-does-not-exist :ignore)
    (uiop:delete-directory-tree (uiop:ensure-directory-pathname tmp-cwd)
                                :validate t
                                :if-does-not-exist :ignore)))

(defun test-addon-resolution ()
  "Test addon discovery and explicit addon selection."
  (let* ((suffix (write-to-string (get-universal-time)))
         (addons-root (format nil "/tmp/filemaid-addons-~A/" suffix))
         (addon-file (format nil "~Aexample-addon.lisp" addons-root))
         (old-addons-root filemaid::*addons-root*)
         (old-enabled-addons filemaid::*enabled-addons*))
    (ensure-directories-exist addons-root)
    (with-open-file (stream addon-file :direction :output :if-exists :supersede :if-does-not-exist :create)
      (format stream "(in-package :filemaid)~%"))
    (setf filemaid::*addons-root* addons-root)
    (setf filemaid::*enabled-addons* nil)
    (assert-true (find (pathname addon-file)
                       (filemaid:discover-addon-files)
                       :test #'equal)
                 "discover-addon-files should detect addon file")
    (setf filemaid::*enabled-addons* '("example-addon"))
    (assert-true (find (pathname addon-file)
                       (filemaid:resolve-enabled-addon-files)
                       :test #'equal)
                 "resolve-enabled-addon-files should resolve addon by name")
    (setf filemaid::*addons-root* old-addons-root)
    (setf filemaid::*enabled-addons* old-enabled-addons)
    (delete-file addon-file)
    (uiop:delete-directory-tree (uiop:ensure-directory-pathname addons-root)
                                :validate t
                                :if-does-not-exist :ignore)))
