(in-package :filemaid.tests)

(defun test-cli-parsing-helpers ()
  "Test CLI parsing helpers for backend and policy flags."
  (assert-true (eql :auto (filemaid::normalize-watch-backend nil))
               "default backend should be :auto")
  (assert-true (eql :poll (filemaid::normalize-watch-backend "poll"))
               "poll backend should parse")
  (assert-true (eql :inotify (filemaid::normalize-watch-backend "inotify"))
               "inotify backend should parse")
  (assert-true (eql :auto (filemaid::normalize-watch-backend "invalid"))
               "invalid backend should fallback to :auto")
  (assert-true (= 3 (filemaid::parse-positive-integer "3" 1))
               "positive integer parse should succeed")
  (assert-true (= 1 (filemaid::parse-positive-integer "0" 1))
               "zero should fallback to default")
  (assert-true (= 2 (filemaid::parse-positive-integer "abc" 2))
               "invalid integer should fallback to default")
  (assert-true (eql :error-on-conflict (filemaid::normalize-conflict-policy nil))
               "default conflict policy should be :error-on-conflict")
  (assert-true (eql :skip-on-conflict (filemaid::normalize-conflict-policy "skip-on-conflict"))
               "skip-on-conflict should parse")
  (assert-true (eql :priority (filemaid::normalize-conflict-policy "priority"))
               "priority conflict policy should parse")
  (assert-true (eql :rename (filemaid::normalize-file-conflict-policy "rename"))
               "file conflict policy rename should parse")
  (assert-true (eql :text (filemaid::normalize-diagnostics-format nil))
               "default diagnostics format should be :text")
  (assert-true (eql :json (filemaid::normalize-diagnostics-format "json"))
               "json diagnostics format should parse")
  (assert-true (filemaid::automated-mode-p (list "--yes"))
               "--yes should enable automated mode")
  (assert-true (eql (filemaid:conflict-policy)
                    (filemaid::resolve-interactive-policy nil nil))
                "no conflicts should keep configured policy"))

(defun test-conflict-profile-persistence ()
  "Test persisted profile load/save round-trip."
  (let* ((suffix (write-to-string (get-universal-time)))
         (profile-path (format nil "/tmp/filemaid-conflict-profile-~A.sexp" suffix))
         (old-path filemaid::*conflict-resolution-profile-path*)
         (old-profile filemaid::*conflict-resolution-profile*))
    (setf filemaid::*conflict-resolution-profile-path* profile-path)
    (setf filemaid::*conflict-resolution-profile* nil)
    (filemaid:conflict-profile-set "k" :left)
    (filemaid:save-conflict-resolution-profile)
    (setf filemaid::*conflict-resolution-profile* nil)
    (filemaid:load-conflict-resolution-profile :force t)
    (assert-true (eql :left (filemaid:conflict-profile-get "k"))
                 "saved conflict profile decision should reload")
    (delete-file profile-path)
    (setf filemaid::*conflict-resolution-profile-path* old-path)
    (setf filemaid::*conflict-resolution-profile* old-profile)))
